# Generated by Django 3.1.7 on 2021-04-04 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerName', models.CharField(max_length=20)),
                ('customerEmail', models.EmailField(max_length=50)),
                ('customerContact', models.CharField(max_length=11)),
                ('customerPassword', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Customer Info',
            },
        ),
        migrations.CreateModel(
            name='TemporaryC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerName', models.CharField(max_length=20)),
                ('customerPassword', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Customer Temporary Data',
            },
        ),
    ]
