# Generated by Django 3.1.7 on 2021-04-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customerImage',
            field=models.ImageField(default='default.png', upload_to='customer_img/images'),
        ),
    ]
