# Generated by Django 3.1.7 on 2021-05-23 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_auto_20210414_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='sellerToken',
            field=models.CharField(default='0000', max_length=4),
        ),
    ]
